name: Alex Minnaar
description: >
    Alex Minnaar's Blog
about: >
    Welcome to my blog, I hope you enjoy it.  My name is Alex Minnaar and I work in the areas of machine learning/data science/software engineering. My contact info's on the top right if you'd like to reach out.
url: ""
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 100

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           alexminnaar
  email:          "minnaaralex@gmail.com"
  # Social networking links used in footer. Update and remove as you like.
  github: https://github.com/alexminnaar
  linkedin: https://www.linkedin.com/in/alex-minnaar-853a2356/
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
